version: '3.8'

services:
  economist-assistant:
    build: .
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - PYTHONPATH=/app
      - DATA_DIR=/app/data
    stdin_open: true
    tty: true
    restart: unless-stopped