$schema: "https://raw.githubusercontent.com/lastmile-ai/mcp-agent/main/schema/mcp-agent.config.schema.json"

# Configuración de Azure OpenAI (usando tus variables de entorno existentes)
openai:
  api_key: "${AZURE_OPENAI_API_KEY}"
  api_base: "${AZURE_OPENAI_API_BASE}"
  api_version: "${AZURE_OPENAI_API_VERSION}"
  api_type: "azure"

# Configuración de servidores MCP (deshabilitados por ahora para simplificar)
mcp:
  servers: {}
    # fetch:
    #   command: "npx"
    #   args: ["-y", "@modelcontextprotocol/server-fetch"]
    # filesystem:
    #   command: "npx"
    #   args: ["-y", "@modelcontextprotocol/server-filesystem", "."]