# Configuración de Servidores MCP para EconomIAssist
# Este archivo define los servidores MCP disponibles y su configuración

servers:
  # Servidor Tavily - Búsqueda Web
  tavily:
    name: "tavily"
    description: "Servidor MCP para búsqueda web usando Tavily API"
    command: ["npx", "-y", "@modelcontextprotocol/server-tavily"]
    auto_connect: true
    priority: 1
    capabilities:
      - "web_search"
      - "news_search"
      - "real_time_data"
    environment:
      TAVILY_API_KEY: "${TAVILY_API_KEY}"
    tools:
      - search
      - news_search
    resources: []
    
  # Servidor Simple Finance - Datos Financieros Locales
  simple_finance:
    name: "simple_finance"
    description: "Servidor MCP local para datos financieros y transacciones"
    command: ["python", "src/mcp_servers/simple_finance.py"]
    auto_connect: true
    priority: 2
    capabilities:
      - "finance_data"
      - "transactions"
      - "currency_exchange"
    environment: {}
    tools:
      - get_exchange_rate
      - add_transaction
      - get_transactions
      - get_balance
    resources:
      - "file:///transactions.json"
      - "file:///accounts.json"

  # Servidor Weather (opcional)
  weather:
    name: "weather"
    description: "Servidor MCP para información meteorológica"
    command: ["npx", "-y", "@modelcontextprotocol/server-weather"]
    auto_connect: false
    priority: 3
    capabilities:
      - "weather_data"
      - "forecasts"
    environment:
      WEATHER_API_KEY: "${WEATHER_API_KEY}"
    tools:
      - get_weather
      - get_forecast
    resources: []

  # Servidor Calendar (futuro)
  calendar:
    name: "calendar"
    description: "Servidor MCP para gestión de calendario y eventos"
    command: ["python", ""]
    auto_connect: false
    priority: 4
    capabilities:
      - "calendar_management"
      - "event_scheduling"
    environment: {}
    tools:
      - add_event
      - get_events
      - update_event
      - delete_event
    resources:
      - "file:///calendar.json"

# Configuración global de MCP
settings:
  protocol_version: "2024-11-05"
  client_info:
    name: "EconomIAssist"
    version: "1.0.0"
  connection_timeout: 30
  retry_attempts: 3
  log_level: "INFO"

# Mapeo de capacidades a casos de uso
capability_mapping:
  web_search:
    use_cases:
      - "búsqueda de tasas de cambio actuales"
      - "noticias financieras"
      - "información económica en tiempo real"
    preferred_server: "tavily"
    
  finance_data:
    use_cases:
      - "gestión de transacciones personales"
      - "cálculo de balances"
      - "conversiones de moneda"
    preferred_server: "simple_finance"
    
  weather_data:
    use_cases:
      - "pronóstico del tiempo"
      - "condiciones climáticas"
    preferred_server: "weather"
    
  calendar_management:
    use_cases:
      - "agendar eventos"
      - "consultar calendario"
      - "recordatorios"
    preferred_server: "calendar"